"""Pure, deterministic policy-core primitives for X5-RB-VoE."""

from rb_voe.core.counterexample import (
    CounterexampleCandidate,
    CounterexampleSearchResult,
    DecisionAssessment,
    HarmAssessment,
    PatchOperation,
    PerturbationRegistry,
    RegisteredPerturbation,
    StatePatch,
    apply_registered_perturbation,
    default_harm_assessment,
    find_best_counterexample,
    search_registered_perturbations,
)
from rb_voe.core.evidence_dag import (
    EvidenceDAG,
    EvidenceGraphError,
    EvidenceIssue,
    EvidenceIssueCode,
    EvidenceValidation,
    validate_records,
)
from rb_voe.core.invariants import (
    HardInvariantViolation,
    InvariantEvaluator,
    InvariantFailure,
    InvariantOperator,
    InvariantReport,
    InvariantRule,
    evaluate_evidence_invariants,
    evaluate_hard_invariants,
    evaluate_physical_evidence_invariants,
)
from rb_voe.core.options import SequenceOutcome, SequenceOutcomeModel
from rb_voe.core.policy import (
    PolicyEvidenceAdmission,
    PolicyEvidenceAdmissionError,
    PolicyEvidenceAdmissionReport,
    canonical_policy_search_state,
)
from rb_voe.core.task_automaton import (
    LEGAL_TRANSITIONS,
    TERMINAL_STATES,
    IllegalTransition,
    TaskAutomaton,
    TaskState,
    TaskTransition,
    TransitionFailure,
    TransitionResult,
)

__all__ = [
    "LEGAL_TRANSITIONS",
    "TERMINAL_STATES",
    "CounterexampleCandidate",
    "CounterexampleSearchResult",
    "DecisionAssessment",
    "EvidenceDAG",
    "EvidenceGraphError",
    "EvidenceIssue",
    "EvidenceIssueCode",
    "EvidenceValidation",
    "HardInvariantViolation",
    "HarmAssessment",
    "IllegalTransition",
    "InvariantEvaluator",
    "InvariantFailure",
    "InvariantOperator",
    "InvariantReport",
    "InvariantRule",
    "PatchOperation",
    "PolicyEvidenceAdmission",
    "PolicyEvidenceAdmissionError",
    "PolicyEvidenceAdmissionReport",
    "PerturbationRegistry",
    "RegisteredPerturbation",
    "StatePatch",
    "SequenceOutcome",
    "SequenceOutcomeModel",
    "TaskAutomaton",
    "TaskState",
    "TaskTransition",
    "TransitionFailure",
    "TransitionResult",
    "apply_registered_perturbation",
    "canonical_policy_search_state",
    "default_harm_assessment",
    "evaluate_evidence_invariants",
    "evaluate_hard_invariants",
    "evaluate_physical_evidence_invariants",
    "find_best_counterexample",
    "search_registered_perturbations",
    "validate_records",
]
